#!/usr/bin/env python3
"""
BTCLI Secure Environment Setup
Outsider Telegram — Bittensor operations

This script sets up a secure, isolated BTCLI environment:
- Dedicated wallet directory (outside the git repo)
- Read-only wallet for chain queries (no signing keys needed)
- Config file pointing to Finney mainnet
- Environment validation

SECURITY RULES:
  - Wallets are stored in ~/.bittensor/wallets/ (NEVER inside the project)
  - .env contains NO private keys — only API keys for 3rd party services
  - BTCLI operations use --no-prompt and --wallet-path flags
  - Coldkey mnemonics are NEVER stored in plaintext
"""

import os
import json
import subprocess
import sys
from pathlib import Path

# ─── PATHS ─────────────────────────────────────────────────────────────────
WALLET_BASE = Path.home() / ".bittensor" / "wallets"
CONFIG_DIR  = Path.home() / ".bittensor"
CONFIG_FILE = CONFIG_DIR / "config.yaml"
PROJECT_ROOT = Path(__file__).parent.parent  # outsider-telegram/

# ─── FINNEY MAINNET ─────────────────────────────────────────────────────────
FINNEY_ENDPOINT = "wss://entrypoint-finney.opentensor.ai:443"
TESTNET_ENDPOINT = "wss://test.finney.opentensor.ai:443"


def check_btcli():
    result = subprocess.run(["btcli", "--version"], capture_output=True, text=True)
    if result.returncode != 0:
        print("❌ btcli not found. Run: pip install git+https://github.com/opentensor/btcli.git")
        sys.exit(1)
    version = result.stdout.strip()
    print(f"✅ {version}")


def check_bittensor():
    try:
        import bittensor
        print(f"✅ bittensor {bittensor.__version__}")
    except ImportError:
        print("❌ bittensor not installed. Run: pip install bittensor")
        sys.exit(1)


def create_wallet_dir():
    WALLET_BASE.mkdir(parents=True, exist_ok=True)
    print(f"✅ Wallet directory: {WALLET_BASE}")


def write_btcli_config():
    """Write btcli config.yaml pointing to Finney mainnet."""
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    config = f"""# BTCLI Configuration — Outsider Telegram
# Auto-generated by btcli-env/setup.py
# DO NOT COMMIT THIS FILE

chain:
  network: finney
  subtensor.chain_endpoint: {FINNEY_ENDPOINT}

wallet:
  path: {WALLET_BASE}

logging:
  debug: false
  trace: false
"""
    CONFIG_FILE.write_text(config)
    print(f"✅ BTCLI config written: {CONFIG_FILE}")


def check_network_connection():
    """Quick connectivity check to Finney (bittensor v10 async API)."""
    import asyncio
    async def _check():
        import bittensor as bt
        async with bt.AsyncSubtensor(network="finney") as sub:
            block = await sub.substrate.get_block_number(None)
            return block
    try:
        print("   Connecting to Finney mainnet...")
        block = asyncio.run(_check())
        print(f"✅ Finney connected — current block: {block:,}")
        return True
    except Exception as e:
        print(f"⚠️  Network check failed: {e}")
        print("   (This is OK if you're offline — chain queries won't work)")
        return False


def list_wallets():
    """List all wallets currently configured."""
    if not WALLET_BASE.exists():
        print("   No wallets configured yet.")
        return
    wallets = [d.name for d in WALLET_BASE.iterdir() if d.is_dir()]
    if not wallets:
        print("   No wallets yet — create one with btcli-env/wallet.py create")
    else:
        print(f"   Wallets found: {', '.join(wallets)}")


def verify_gitignore():
    """Make sure sensitive paths are gitignored."""
    gitignore = PROJECT_ROOT / ".gitignore"
    required = [".env", "*.key", "*.mnemonic", "wallets/", "__pycache__/"]
    if gitignore.exists():
        content = gitignore.read_text()
        missing = [r for r in required if r not in content]
        if missing:
            with open(gitignore, "a") as f:
                f.write("\n# Security — BTCLI\n")
                for item in missing:
                    f.write(f"{item}\n")
            print(f"✅ .gitignore updated with: {missing}")
        else:
            print("✅ .gitignore security rules OK")


def print_security_rules():
    print("""
╔══════════════════════════════════════════════════════╗
║              BTCLI SECURITY RULES                    ║
╠══════════════════════════════════════════════════════╣
║  ✅ Wallets stored in ~/.bittensor/wallets/          ║
║  ✅ NEVER inside the git repo                        ║
║  ✅ NEVER commit .env or any key file                ║
║  ✅ Use --coldkey-ss58 for read-only queries         ║
║  ✅ Coldkey password required for all transfers      ║
║  ✅ Use testnet first for any new operation          ║
╚══════════════════════════════════════════════════════╝
""")


def main():
    print("\n🔧 OUTSIDER TELEGRAM — BTCLI Environment Setup\n")
    check_btcli()
    check_bittensor()
    create_wallet_dir()
    write_btcli_config()
    verify_gitignore()
    connected = check_network_connection()
    list_wallets()
    print_security_rules()

    if connected:
        print("✅ Environment ready. Run: python btcli-env/query.py to test chain queries.")
    else:
        print("⚠️  Environment ready (offline mode). Connect to internet to run chain queries.")


if __name__ == "__main__":
    main()
